import type { AiGenerateInput, AiGenerateResult, AiProvider } from "./ai-provider.js";

export type MockAiProviderOptions = {
  model?: string;
  content?: unknown;
};

export class MockAiProvider implements AiProvider {
  readonly name = "mock";
  readonly model: string;

  constructor(private readonly options: MockAiProviderOptions = {}) {
    this.model = options.model ?? "mock-docform";
  }

  async generateStructured(_input: AiGenerateInput): Promise<AiGenerateResult> {
    return {
      content: this.options.content ?? createDefaultMockContent(),
      model: this.model,
      usage: {
        inputTokens: 0,
        outputTokens: 0
      }
    };
  }
}

function createDefaultMockContent(): unknown {
  return {
    templateId: "minimal",
    styleProfile: {
      tone: "office",
      density: "normal",
      fontScale: "normal"
    },
    document: {
      metadata: {
        title: "AI Generated Document",
        language: "en"
      },
      blocks: [
        { type: "heading", level: 1, text: "AI Generated Document" },
        { type: "paragraph", text: "This document was generated by the mock DocForm AI provider." }
      ]
    }
  };
}
